### ISSUE TITLE
Face detector 和landmark detector的模型会开源么？

### ISSUE THREAD

**Issue by lyyiangang** [alibaba/MNNKitDemo#1]
请问对应的模型和face track的代码会开源么？

**Comment by xuguozhi** [comment]
希望能够了解106point的原理 模型结构

**Comment by suancaiyu** [comment]
MNNKit仅以SDK的形式开放AI能力，不开放源码，请参考我们的[license](https://github.com/alibaba/MNNKitDemo/blob/master/license)
