### ISSUE TITLE
ios 编译报错

### ISSUE THREAD

**Issue by ChinaJackSion** [alibaba/MNNKitDemo#5]
很多方法是不是都变了，看方法的大小写不一样
![屏幕快照 2020-02-08 17 45 13](https://user-images.githubusercontent.com/15258279/74083062-d22ffa00-4a9a-11ea-9300-c8b303845cde.png)
![屏幕快照 2020-02-08 17 45 25](https://user-images.githubusercontent.com/15258279/74083066-dbb96200-4a9a-11ea-8242-83633f65ffa5.png)

**Comment by suancaiyu** [comment]
目前还没有正式对外发布，有一些内部的修改，这几天会有更新，谢谢关注~
